version: '3'
services:
  postgres:
    image: postgres:13
    container_name: rodo-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: rodo_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - rodo-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
    container_name: rodo-backend
    ports:
      - "3011:3011"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      NODE_ENV: development
      PORT: 3011
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/rodo_db?sslmode=disable
      JWT_SECRET: rodo_secret_key_change_in_production
      JWT_EXPIRATION: 3600
      CORS_ORIGIN: http://localhost:3010
    networks:
      - rodo-network

  frontend:
    build:
      context: .
    container_name: rodo-frontend
    ports:
      - "3010:3010"
    depends_on:
      - backend
    environment:
      PORT: 3010
      REACT_APP_API_URL: http://localhost:3011/api/v1
      REACT_APP_WS_URL: ws://localhost:3011/ws
    networks:
      - rodo-network

networks:
  rodo-network:
    driver: bridge

volumes:
  postgres_data:
