version: '3'
services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: rodo_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
    ports:
      - "3011:3011"
    depends_on:
      - postgres
    environment:
      NODE_ENV: development
      PORT: ${BACKEND_PORT}
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/rodo_db
      JWT_SECRET: rodo_secret_key_change_in_production
      JWT_EXPIRATION: 3600
      CORS_ORIGIN: http://localhost:3010

  frontend:
    build:
      context: .
    ports:
      - "3010:3010"
    depends_on:
      - backend
    environment:
      REACT_APP_API_URL: http://localhost:3011/api/v1
      PORT: ${FRONTEND_PORT}

volumes:
  postgres_data:
